### ISSUE TITLE
VDIF EDV 1, 3 `sample_rate` is not well defined

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#135]
EDV [1](http://www.vlbi.org/vdif/docs/vdif_extension_0x01.pdf) and [3](http://www.vlbi.org/vdif/docs/vdif_extension_0x03.pdf) have a "sample rate" in their headers in either ksps or Msps.  Our sample file  (EVN/VLBA PSR B1957+20 observation, EDV 3) sets sample rate to the bandwidth (16 MHz) rather than the sampling rate (32 MHz, since it's real samples).  We therefore aren't certain how to treat "sample rate" (if we should use it at all).

Also, EDV 3 only allows for 2 bps real samples (EDV 1 is unclear about this), but our sample rate getter assumes complex data is possible, and is sampled at half the rate real data is for the same bandwidth.

**Comment by mhvk** [comment]
Comment: the "EDV 3 only allows for 2 bps real samples" is indeed in the documentation, but with an "as of now" modifier - they suggest this may change. So, perhaps no real reason to forbid it. Or, generous on input, strict on output, have a warning for complex and/or bps!=2 EDV3 output.

For reading, it might be good generally to attempt to determine a frame rate by scanning a file...

**Comment by cczhu** [comment]
I e-mailed Walter Brisken about this issue, and his response was:

"I really suggest you not rely on information in these extended headers. They can be useful as a cross-check against reality, but since the information they provide is so different depending on the source of the data they can't be used definitively for any purpose."

He also says EDV 3's sampling rate assumes complex samples, which is why it's equal to the bandwidth.  He's never seen EDV 1 data.

From that, I think we should make the VDIF stream reader use `_get_frame_rate` in all cases, and leave cross-checking the derived rate against the header sampling rate to the users.  For almost all use cases, this only means a longer load time for the stream reader (and will also make our test suite take longer).

**Comment by mhvk** [comment]
I think there are multiple parts to this issue:
1. Update docstrings and possibly code to reflect that the sample rate in EDV 3 is for complex samples; we can assume the same holds for EDV 1 but should have a note that it may be wrong. This would solve the issue here in a limited sense.
2. Implement using `_get_frame_rate` by default, with perhaps a backup for short files of using the built-in one. This would seem to be a new issue, about generally trying to infer from data rather than rely on headers.
3. Ensure we have a general way to check files and get information like this. This really is part of #145.
