### ISSUE TITLE
Can glossary terms look different from links?

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#171]
E.g., could they be in italics? It would be nice if there was a visual clue.

**Comment by cczhu** [comment]
The simple attempt at doing this, `*:term:`something`*` (or `:term:`*something* <something>`), doesn't work because Sphinx doesn't support nested markup.  The more complicated way of doing it (I think) is creating a custom Sphinx directive that replicates most of the code in [the `Glossary` class an `make_glossary_term` function](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/std.py), but I can't parse how either of these work.

**Comment by mhvk** [comment]
I think `term` is a sphinx "role" which it may (or may not) be possible to set a specific way for in the html (or CSS?) file. Alternatively, I guess we could add quotes around it by hand...

p.s. It also seems one can define a custom role that is a combination of multiple things [1], but that would seem to go the wrong way around.

[1] http://docutils.sourceforge.net/docs/ref/rst/directives.html#role

**Comment by cczhu** [comment]
`term` is indeed a role, though I couldn't find a corresponding CSS class whose properties I can tweak.  Your request is definitely possible - I can alter the `a` class in a custom .css file to italicize every hyperlink, but the API hyperlinks remain bolded, so they must be getting additional formatting information from somewhere.  A decent amount of Googling turned up nothing, however.

**Comment by mhvk** [comment]
OK, thanks for checking. Not a high priority, obviously.

**Comment by mhvk** [comment]
Seems too difficult, so closing.
