### ISSUE TITLE
Warning message on reading Guppi format header

### ISSUE THREAD

**Issue by luojing1211** [mhvk/baseband#282]
There is a Warning message show up when reading Guppi format header. 
Messages:
WARNING: VerifyWarning: Verification reported errors: [astropy.io.fits.verify]
WARNING:astropy:VerifyWarning: Verification reported errors:
WARNING: VerifyWarning: Card 'DROPAVG' is not FITS standard (invalid value string: '1.00284e-193').  Fixed 'DROPAVG' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING:astropy:VerifyWarning: Card 'DROPAVG' is not FITS standard (invalid value string: '1.00284e-193').  Fixed 'DROPAVG' card to meet the FITS standard.
WARNING: VerifyWarning: Note: PyFITS uses zero-based indexing.
 [astropy.io.fits.verify]
WARNING:astropy:VerifyWarning: Note: PyFITS uses zero-based indexing.

How can we switch if off?

**Comment by mhvk** [comment]
@luojing1211 - can you give me the path to the file? I don't get any warnings on the sample file in baseband...

It should be as simple as putting a warnings filter somewhere...

**Comment by luojing1211** [comment]
I did not see it for all the GPUs. But one below has this issue. 
/mnt/scratch-lustre/mahajan/Ar_P3229/B1937+21_58245/gpu06/puppi_58245_B1937+21_0799.0012.raw'

**Comment by mhvk** [comment]
OK, I can now reproduce it. The down-the-line problem is that `astropy.io.fits.header.Header` uses `str()` on its cards and that runs a verification. One can fix it by marking all cards as verified (see #283). This will slightly slow down reading a header, but since the payloads are always very large, I think it doesn't matter too much.
