### ISSUE TITLE
Add CHIME HDF5 Gated format

### ISSUE THREAD

**Issue by luojing1211** [mhvk/baseband#487]
Is it a good idea to add CHIME HDF5 Gated format to baseband?  It is not a standard format yet. I think it would be convenient for us just package it in one package.

**Comment by mhvk** [comment]
I think it can easily be developped stand-alone first, just like I did with `hdf5` in baseband-tasks. Note that like that hdf5 format, one can then register the format in `baseband.io`, so that it is available in `baseband.open`.

My overall sense is that `baseband` itself should contain formats that have some sort of defined standard, and ideally are used in more than one place.
