### ISSUE TITLE
User is allowed to seek time outside the file's bounds without warning

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#59]
The .seek() function in VLBIStreamReaderBase does not check to see if the offset provided is valid.

It would be helpful if the seek function threw an error if the user attempts to seek an offset out of the bounds of the data file.

**Comment by mhvk** [comment]
It just mimics the standard behaviour of filehandlers. The one issue with checking is that it is actually not trivial to know how many samples there are in the file: it needs finding the last header, assuming there are no holes, etc. So, implementing the check could mean that files that are "mostly readable" become "unreadable". I guess my bottom line would be that it would be up to the user to check (the total number of samples can be accessed via `fh.size`).

That said, documenting this would probably be good!  Maybe just mention it in the `.seek` docstring?

**Comment by theXYZT** [comment]
Would it be possible to get a function that returns a boolean based on whether the file is readable at the current seek position? Or is there already one?

**Comment by mhvk** [comment]
But what's so hard about `0 <= fh.tell() < fh.size`? (where I assume generally one does not need to check for positive). 

Note: I could see use in a general function that checks one is at the start of a header, etc.

**Comment by theXYZT** [comment]
You mentioned that some files could have holes. Unless I am mistaken, wouldn't that indicate that the file is unreadable somewhere in the middle of the file? So, `0 <= fh.tell() < fh.size` should only work if you are sure the file has no holes? Or have I misunderstood what holes are.

**Comment by mhvk** [comment]
Yes, you're right, which is partially why I'm not quite sure how to implement a function that would tell whether one can read at a given location. Inside code, maybe put the read inside a `try/except` block...

**Comment by mhvk** [comment]
p.s. Separately, not sure under what conditions `fh.read()` should even fail. I think the normal bahviour is to return 0 bytes, so perhaps this should just return 0 samples...

**Comment by theXYZT** [comment]
That would work. Instead of throwing an error, returning an empty array would be a much better solution. That way you can do boolean checks too: `if fh.read(N): #do something`

**Comment by mhvk** [comment]
Well, that specific example does not work (would error for any sized array), but I think we're converging: the wishlist item would be to just return an empty data set if one is outside of range.

**Comment by theXYZT** [comment]
How would that behave if the user requests N samples but there are fewer than N samples to read?

**Comment by mhvk** [comment]
if we make it like normal filehandlers, you get out only what is available, i.e., we'd have, similarly,
```
Read and return up to n bytes.
```
except samples instead of bytes.

**Comment by mhvk** [comment]
Labelling this with `docs` as I think the main conclusion is that the behaviour at end of file should be properly documented.

**Comment by cczhu** [comment]
Currently seeking past the end of file using the sample counter, then attempting `fh.read()` returns
```
ValueError: negative dimensions are not allowed
```
(seeking to just before the end of file and reading more data than exists returns the more helpful `EOFError: `, but still isn't returning up to n samples.)  I understand @mhvk's argument that the end of file is sometimes poorly defined, but since `fh.size` is actually being used, wouldn't the user still encounter that error for a "mostly readable" file when Baseband fails to properly find the last header?

**Comment by mhvk** [comment]
Currently, I think a user can happily open a file which is corrupt at the end and read until the place where it is corrupted, including skipping forward/backward. If we start sanity-checking the input, then that no longer is possible.

**Comment by cczhu** [comment]
Ahh, I should clarify - I'm testing with the sample VDIF file.  Seeking to beyond the EOF and reading any finite number of samples returns an EOFError, as does seeking to just before the EOF and reading too many samples.  The only thing that returns `ValueError: negative dimensions are not allowed` is seeking to beyond the EOF and reading an unlimited number of samples, since in this case you must know the size of the file.  Should we close that loophole by returning an EOFError if the count is negative?

**Comment by mhvk** [comment]
Sure, makes sense to ensure it raises `EOFError` for consistency. Perhaps surprisingly, this in itself is inconsistent with the standard python reader: that just returns an empty byte string, also if you give a specific number to read. But since we need to interpret any bytes, I think `EOFError` is not inappropriate.
