### ISSUE TITLE
Some stream reader attributes aren't documented

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#84]
Sphinx's automodapi is unable to document instance attributes (for obvious reasons), but this leaves a number of useful attributes initialized by stream readers, such as `nchan`, `frames_per_second` and even `header0`, [undocumented in the API](https://baseband.readthedocs.io/en/latest/api/baseband.vdif.base.VDIFStreamReader.html#baseband.vdif.base.VDIFStreamReader).

One solution would be to include these in the class whose `__init__` creates them, eg. `nchan` in `VLBIStreamBase`.  This does, however, increase clutter.  Strangely, attribute docstrings show up in the API of their defined class, but only the attribute shows up in subclasses (if :inherited-members: is used).

**Comment by mhvk** [comment]
On that last point: I think the issue is that python doesn't really associate a docstring with an attribute at all; it is just that sphinx picks out a docstring if it is given directly after the attribute.

On the larger question: we may be stuck with defining properties for these. As long as there are only a few, this would be OK. It also prevents overwriting of things that should never change...
